const router = require('express').Router()
const TaskController = require('../controllers/taskController')
const authentication = require('../middleware/authentication')
const authorization = require('../middleware/authorization')
router.get('/', authentication,TaskController.getTask)
router.post('/', authentication,TaskController.createTask)
router.get('/:id', authentication,TaskController.getById)
router.put('/:id',authentication, authorization, TaskController.put)
router.patch('/:id', authentication, authorization,TaskController.patch)
router.delete('/:id', authentication, authorization,TaskController.remove)
module.exports = router